# fly.toml app configuration file generated for codespark on 2023-08-17T19:28:14-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "codespark"
primary_region = "yyz"
console_command = "/code/code_spark/manage.py shell"

[build]

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/code/code_spark/static"
  url_prefix = "/static/"
